application: mmmorblegh
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /static
  static_dir: static

- url: /static/stylesheets
  static_dir: static/stylesheets

- url: /static/stylesheets/images
  static_dir: static/images

- url: /static/scripts
  static_dir: static/scripts

- url: /mail_feedback
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest